# Constantes de DuocLaboral (Carreras, Regiones, Comunas)

DUOC_CARRERAS = {
    "Actuación": "288",
    "Administración de Empresas": "4",
    "Administración de empresas m/marketing": "292",
    "Administración de recursos humanos": "293",
    "Administración de Redes y Telecomunicaciones": "294",
    "Administración de ventas": "769",
    "ADMINISTRACIÓN EN TURISMO Y HOSPITALIDAD": "2106",
    "Administración financiera": "296",
    "Administración Hotelera": "297",
    "Administración pública": "754",
    "Administración turística": "743",
    "Administrador de Infraestructura y Plataformas Tecnológicas": "289",
    "Analista programador computacional": "301",
    "Animación digital": "302",
    "Asistente ejecutivo": "748",
    "Auditoría": "304",
    "AUDITORÍA Y ANÁLISIS DE NEGOCIOS": "2870",
    "Comercio exterior": "305",
    "Comunicación audiovisual": "306",
    "Contabilidad general m/Legislación tributaria": "307",
    "CONTABILIDAD TRIBUTARIA": "1714",
    "DESARROLLO DE APLICACIONES": "1716",
    "Desarrollo y Diseño Web": "351",
    "Dibujo y Modelamiento Arquitectónico y Estructural": "308",
    "Dirección en administración hotelera": "756",
    "Diseño de ambientes": "311",
    "Diseño de muebles": "768",
    "Diseño de vestuario": "313",
    "Diseño gráfico": "314",
    "Diseño Industrial": "315",
    "Ecoturismo": "316",
    "Fisioterapia": "318",
    "Gastronomía": "319",
    "Gastronomía internacional": "320",
    "Gestión comercial": "750",
    "Ilustración": "321",
    "ILUSTRACIÓN PARA CONTEXTOS GLOBALES": "2872",
    "Informática biomédica": "322",
    "Ingeniería agrícola": "323",
    "Ingeniería en acuicultura": "325",
    "Ingeniería en administración": "327",
    "Ingeniería en administración de recursos humanos": "328",
    "Ingenieria en administración hotelera": "762",
    "INGENIERÍA EN ADMINISTRACIÓN MENCIÓN INNOVACIÓN Y EMPRENDIMIENTO": "1715",
    "Ingeniería en administración turística": "761",
    "Ingeniería en automatización de procesos industriales": "755",
    "INGENIERÍA EN AUTOMATIZACIÓN Y CONTROL INDUSTRIAL": "2874",
    "INGENIERÍA EN CIBERSEGURIDAD": "2876",
    "INGENIERÍA EN CIENCIA DE DATOS": "2875",
    "Ingenieria en comercio exterior": "330",
    "Ingeniería en conectividad y redes": "331",
    "Ingeniería en Construcción": "332",
    "INGENIERÍA EN DESARROLLO DE SOFTWARE": "1717",
    "Ingeniería en electricidad y automatización industrial": "333",
    "Ingeniería en electrónica industrial": "744",
    "Ingeniería en gestión comercial": "336",
    "INGENIERÍA EN GESTIÓN DE PERSONAS": "2869",
    "Ingenieria en gestion de tecnologías": "767",
    "Ingeniería en gestión de ventas": "766",
    "Ingeniería en Gestión Logística": "340",
    "Ingeniería en informática": "341",
    "Ingeniería en Infraestructura y Plataformas Tecnológicas": "342",
    "Ingeniería en Mantenimiento Industrial": "991",
    "Ingenieria en maquinaria y vehículos pesados": "343",
    "Ingeniería en marketing": "344",
    "Ingeniería en mecánica automotriz y autotrónica": "345",
    "Ingeniería en medio ambiente": "346",
    "Ingeniería en prevención de riesgos": "348",
    "Ingeniería en Redes y Telecomunicaciones": "988",
    "Ingeniería en sonido": "349",
    "INGENIERÍA INDUSTRIAL": "2873",
    "Preparador físico": "350",
    "Publicidad": "110",
    "Publicidad técnica": "760",
    "Relaciones públicas m/marketing": "354",
    "RELACIONES PÚBLICAS Y COMUNICACIÓN ORGANIZACIONAL": "2101",
    "Restauracion patrimonial": "355",
    "Técnico agrícola": "357",
    "Técnico analisis y control ambiental": "747",
    "Técnico audiovisual": "358",
    "Técnico de laboratorio clínico y banco de sangre": "360",
    "Técnico de radiodiagnóstico y radioterapia": "361",
    "Técnico en acuicultura": "362",
    "Técnico en Administración": "1007",
    "Técnico en ambientación y vitrinismo": "752",
    "Técnico en calidad de alimentos": "364",
    "Técnico en construcción": "365",
    "TÉCNICO EN CONTROL Y MONITOREO REMOTO DE PROCESOS MINEROS": "2103",
    "Técnico en diseño gráfico": "751",
    "Técnico en diseño industrial": "763",
    "Técnico en electricidad y automatización industrial": "368",
    "TÉCNICO EN ELECTRICIDAD Y ENERGÍAS RENOVABLES": "2102",
    "Técnico en energías renovables": "371",
    "Técnico en enfermería": "359",
    "Técnico en geología y control de sondaje": "372",
    "Técnico en geomática": "373",
    "Técnico en gestión de eventos": "770",
    "Técnico en gestión logística": "291",
    "Técnico en instalaciones de gas": "374",
    "Técnico en instalaciones sanitarias": "376",
    "Técnico en instalaciones y proyectos eléctricos": "377",
    "Técnico en instrumentación industrial": "378",
    "Técnico en instrumentación y automatización industrial": "757",
    "Técnico en mantenimiento electromecánico": "379",
    "Técnico en mantenimiento electromecanico mención minería": "764",
    "Técnico en mantenimiento industrial": "749",
    "Técnico en mantenimiento predictivo mención minería": "382",
    "Técnico en maquinaria y vehiculos pesados": "383",
    "Técnico en mecánica automotriz y autotrónica": "384",
    "Técnico en nutrición y dietética": "385",
    "Técnico en odontología": "386",
    "TÉCNICO EN OPERACIÓN Y SUPERVISIÓN DE PROCESOS MINEROS": "2104",
    "TÉCNICO EN OPERACIONES LOGÍSTICAS": "2100",
    "Técnico en prevención de riesgos": "387",
    "TÉCNICO EN PRODUCCIÓN GRÁFICA": "966",
    "Técnico en producción industrial de vestuario": "758",
    "Técnico en química y farmacia": "390",
    "Técnico en servicios financieros y bancarios": "765",
    "Técnico en soldadura industrial": "753",
    "Técnico en sonido": "398",
    "Técnico en telecomunicaciones": "394",
    "TÉCNICO EN TRABAJO SOCIAL": "2871",
    "TÉCNICO EN TURISMO Y HOSPITALIDAD": "2105",
    "Técnico en turismo y hotelería": "759",
    "Técnico jurídico": "395",
    "Técnico topógrafo": "396",
    "Técnico veterinario y pecuario": "397",
    "Tourism & hospitality": "399",
    "TOURISM & HOSPITALITY TECHNICIAN": "967",
    "Turismo de aventura": "400",
    "Turismo técnico": "746",
    "Turismo técnico en empresas turísticas": "402",
    "Turismo técnico en servicios áerocomerciales": "403",
    "TURISMO TÉCNICO MENCIÓN EN EMPRESAS TURÍSTICAS": "1718",
    "Turismo y Hotelería": "310",
    "Turismo y hotelería mención servicios aerocomerciales": "771",
}

DUOC_REGIONES = {
    "Región Metropolitana": "1",
    "I Región de Tarapacá": "2",
    "II Región de Antofagasta": "3",
    "III Región de Atacama": "4",
    "IV Región de Coquimbo": "5",
    "V Región de Valparaíso": "6",
    "VI Región del Lib. Gral. Bernardo O´Higgins": "7",
    "VII Región del Maule": "8",
    "VIII Región del Bío - Bío": "9",
    "IX Región de la Araucanía": "10",
    "X Región de Los Lagos": "11",
    "XI Región de Aysén": "12",
    "XII Región de Magallanes": "13",
    "XIV Región de Los Ríos": "14",
    "XV Región de Arica y Parinacota": "15",
    "XVI Región de Ñuble": "4235",
}

DUOC_COMUNAS = {
    "Alhué": "39",
    "Buin": "46",
    "Calera de Tango": "47",
    "Cerrillos": "1",
    "Cerro Navia": "2",
    "Colina": "50",
    "Conchalí": "3",
    "Curacaví": "38",
    "El Bosque": "4",
    "El Monte": "42",
    "Estación Central": "5",
    "Huechuraba": "6",
    "Independencia": "7",
    "Isla de Maipo": "43",
    "La Cisterna": "8",
    "La Florida": "9",
    "La Granja": "10",
    "La Pintana": "11",
    "La Reina": "12",
    "Lampa": "51",
    "Las Condes": "13",
    "Lo Barnechea": "14",
    "Lo Espejo": "15",
    "Lo Prado": "16",
    "Macul": "17",
    "Maipú": "18",
    "María Pinto": "37",
    "Melipilla": "36",
    "Nuñoa": "19",
    "Padre Hurtado": "44",
    "Paine": "48",
    "Pedro Aguirre Cerda": "20",
    "Peñaflor": "45",
    "Peñalolén": "21",
    "Pirque": "34",
    "Providencia": "22",
    "Pudahuel": "23",
    "Puente Alto": "33",
    "Quilicura": "24",
    "Quinta Normal": "25",
    "Recoleta": "26",
    "Renca": "27",
    "San Bernardo": "49",
    "San Joaquín": "28",
    "San José de Maipo": "35",
    "San Miguel": "29",
    "San Pedro": "40",
    "San Ramón": "30",
    "Santiago": "31",
    "Talagante": "41",
    "Til Til": "52",
    "Vitacura": "32",
}

DUOC_MODALIDADES = {
    "Presencial": "0",
    "Remoto": "1",
    "Híbrido": "2",
}

# ─── ChileTrabajos: Ciudades disponibles en el filtro de ubicación ───────────
# Nombre para mostrar → slug (data-seo del <select name="13">)
CT_CIUDADES = {
    "Cualquiera": "",
    # Mapeo de Regiones (DuocLaboral) a la ciudad respectiva en ChileTrabajos
    "Región Metropolitana": "1022",
    "I Región de Tarapacá": "1002",
    "II Región de Antofagasta": "1004",
    "III Región de Atacama": "1007",
    "IV Región de Coquimbo": "1010",
    "V Región de Valparaíso": "1014",
    "VI Región del Lib. Gral. Bernardo O´Higgins": "1028",
    "VII Región del Maule": "1031",
    "VIII Región del Bío - Bío": "1035",
    "IX Región de la Araucanía": "1039",
    "X Región de Los Lagos": "1043",
    "XI Región de Aysén": "1047",
    "XII Región de Magallanes": "1051",
    "XIV Región de Los Ríos": "1041",
    "XV Región de Arica y Parinacota": "1000",
    "XVI Región de Ñuble": "1036",
    # Mapeo de Ciudades/Comunas por ID (ChileTrabajos original)
    "Santiago": "1022",
    "Concepción": "1035",
    "Valparaíso": "1014",
    "Antofagasta": "1004",
    "Rancagua": "1028",
    "Arica": "1000",
    "Putre": "1001",
    "Iquique": "1002",
    "Pozo Almonte": "1003",
    "Tocopilla": "1005",
    "Calama": "1006",
    "Copiapó": "1007",
    "Chañaral": "1008",
    "Vallenar": "1009",
    "La Serena": "1010",
    "Coquimbo": "1011",
    "Ovalle": "1012",
    "Illapel": "1013",
    "La Ligua": "1015",
    "Los Andes": "1016",
    "San Felipe": "1017",
    "Quillota": "1018",
    "San Antonio": "1019",
    "Hanga Roa": "1020",
    "Quilpué": "1021",
    "Colina": "1023",
    "Puente Alto": "1024",
    "San Bernardo": "1025",
    "Melipilla": "1026",
    "Talagante": "1027",
    "San Fernando": "1029",
    "Pichilemu": "1030",
    "Talca": "1031",
    "Curicó": "1032",
    "Linares": "1033",
    "Cauquenes": "1034",
    "Quirihue": "1055",
    "Bulnes": "1056",
    "San Carlos": "1057",
    "Chillán": "1036",
    "Los Ángeles": "1037",
    "Lebu": "1038",
    "Temuco": "1039",
    "Angol": "1040",
    "Valdivia": "1041",
    "La Unión": "1042",
    "Puerto Montt": "1043",
    "Osorno": "1044",
    "Castro": "1045",
    "Chaitén": "1046",
    "Coyhaique": "1047",
    "Puerto Aysén": "1048",
    "Chile Chico": "1049",
    "Cochrane": "1050",
    "Punta Arenas": "1051",
    "Puerto Natales": "1052",
    "Porvenir": "1053",
    "Puerto Williams": "1054",
}
